pub enum Skills {
    Rust,
    RocketRs,
    FullstackWeb,
    DNS,
    Cloudflare,
    WebHosting,
    Linode,
    ServerSideRendering,
    WebTemplating,
    Maud,
    SEO,
    GoogleSEO,
    BingSEO,
    DynamicSitemap,
    HTML,
    CSS,
    Microcontrollers,
    RaspberryPi,
    DynamicParsing,
    UnityEngine,
    CSharp,
    AI,
    ML,
    CustomML,
    DesktopSoftware,
    WindowsSoftware,
    LinuxSoftware,
    MacSoftware,
    WebApps,
    WGPU,
    Winit,
    GUIDesign,
    GUIFrameworkDesign,
    BUI,
    BUIBasic,
    Constrainer,
    AudioVisualization,
    SoftwareAudioPlayback,
    AsyncSoftware,
    RustAsync,
    JavaScript,
    P5JS,
    P5Sound,
    ExpressJS,
    Websockets,
    SocketIO,
    RealTimeMultiplayer,
    WebMultiplayer,
    MultiplayerClientPredicationAndRollback,
    MultiplayerMatchmaking,
    PeripheralDevelopment,
    CAD,
    FreeCAD,
    FDM3DPrinting,
    Debouncing,
    Soldering,
    Arduino,
    CPP,
    OpenSCAD,
    Nginx,
    ReverseProxy,
    Linux,
    Ubuntu,
    NodeJS,
    API,
    ReverseEngineeringAPI,
    RESTAPI,
    BrowserExtensions,
    BrowserExtensionPublishing,
    Python,
    FFmpeg,
    YouTubeAPI,
    C,
    LowLevelEmbeddedSoftware,
    PebbleUI,
    GameDevelopment,
    FirmwareDevelopment,
    FreeRTOSSoftware,
    LittleVGL,
    AndroidNative,
    AndroidLayoutsViews,
    Java,
    MobileApps,
    VRAppDevelopment,
    OpenXR,
    Godot,
    GodotRust,
    FFI,
    DesktopGames,
    WindowsGames,
    TCPSockets,
    RenderShaders,
    WGSL,
    Websites,
    CrossPlatformDesktopMobileWeb,
    ComputeShaders,
    StaticSites,
    CLI,
    Algorithms,
    OCR,
}

impl Skills {
    pub const fn as_str(&self) -> &str {
        use Skills::*;
        match self {
            Rust => "Rust",
            RocketRs => "Rocket.rs",
            FullstackWeb => "fullstack web",
            DNS => "DNS",
            Cloudflare => "Cloudflare",
            WebHosting => "web hosting",
            Linode => "Linode",
            ServerSideRendering => "server-side rendering",
            WebTemplating => "web templating",
            Maud => "Maud",
            SEO => "SEO",
            GoogleSEO => "Google SEO",
            BingSEO => "Bing SEO",
            DynamicSitemap => "dynamic sitemap",
            HTML => "HTML",
            CSS => "CSS",
            Microcontrollers => "microcontrollers",
            RaspberryPi => "Raspberry Pi",
            DynamicParsing => "dynamic parsing",
            UnityEngine => "Unity Engine",
            CSharp => "C#",
            AI => "AI",
            ML => "ML",
            CustomML => "custom ML",
            DesktopSoftware => "desktop software",
            WindowsSoftware => "Windows software",
            LinuxSoftware => "Linux software",
            MacSoftware => "Mac software",
            WebApps => "web apps",
            WGPU => "WGPU",
            Winit => "Winit",
            GUIDesign => "GUI design",
            GUIFrameworkDesign => "GUI framework design",
            BUI => "BUI (my core gui lib)",
            BUIBasic => "BUI Basic (my gui framework)",
            Constrainer => "Constrainer (now \"archived indefinitely\" tool for creating CAD-like GUI)",
            AudioVisualization => "audio visualization",
            SoftwareAudioPlayback => "software audio playback",
            AsyncSoftware => "async software",
            RustAsync => "async in Rust",
            JavaScript => "JavaScript",
            P5JS => "p5.js",
            P5Sound => "p5.sound",
            ExpressJS => "ExpressJS",
            Websockets => "Websockets",
            SocketIO => "socket.io",
            RealTimeMultiplayer => "real-time multiplayer",
            WebMultiplayer => "multiplayer on the web",
            MultiplayerClientPredicationAndRollback => "multiplayer client prediction and rollback",
            MultiplayerMatchmaking => "multiplayer matchmaking",
            PeripheralDevelopment => "peripheral dev",
            CAD => "CAD",
            FreeCAD => "FreeCAD",
            FDM3DPrinting => "FDM 3D Printing",
            Debouncing => "Debouncing",
            Soldering => "Soldering",
            Arduino => "Arduino",
            CPP => "C++",
            OpenSCAD => "OpenSCAD",
            Nginx => "Nginx",
            ReverseProxy => "reverse proxy",
            Linux => "Linux",
            Ubuntu => "Ubuntu",
            NodeJS => "Node.js",
            API => "API",
            ReverseEngineeringAPI => "reverse engineering APIs",
            RESTAPI => "REST API",
            BrowserExtensions => "browser extensions",
            BrowserExtensionPublishing => "browser extension publishing",
            Python => "Python",
            FFmpeg => "FFmpeg",
            YouTubeAPI => "YouTube API",
            C => "C",
            LowLevelEmbeddedSoftware => "low-level/embedded software",
            PebbleUI => "Pebble UI",
            GameDevelopment => "game development",
            FirmwareDevelopment => "firmware development",
            FreeRTOSSoftware => "FreeRTOS software",
            LittleVGL => "LittleVGL",
            AndroidNative => "Android Native",
            AndroidLayoutsViews => "Android layouts/views",
            Java => "Java",
            MobileApps => "mobile apps",
            VRAppDevelopment => "VR app development",
            OpenXR => "OpenXR",
            Godot => "Godot",
            GodotRust => "Rust in Godot",
            FFI => "FFI",
            DesktopGames => "Desktop Games",
            WindowsGames => "Windows Games",
            TCPSockets => "TCP Sockets",
            RenderShaders => "render shaders",
            WGSL => "WGSL",
            Websites => "websites",
            CrossPlatformDesktopMobileWeb => "cross-platform (mobile, desktop, web)",
            ComputeShaders => "compute shaders",
            StaticSites => "static sites",
            CLI => "CLI",
            Algorithms => "algorithms",
            OCR => "OCR"
        }
    }
}